apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-rest-balance-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  PORT: "8900"
  POD_NAME: "go-rest-balance"
  API_VERSION: "1.0"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
